# Generated by Django 3.1.3 on 2020-11-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_stuff', '0002_remove_stuff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='description',
        ),
    ]
